#+title: Outline

* Outline

** Topological materials

*** From high energy phsyics to condensed matter Dirac materials
Start from the Dirac Lagrangian, and show the Weyl decomposition
We exactly recover the Hamiltonian of a dirac cone
See chernodubThermalTransportGeometry2021 eq.~(2)

** Type-II materials
- Introduction
- From tight binding model to linear model
- Tilting term
  - Inversion symmetry vs no inversion symmetry


** The response

*** Magnetization currents
In time reversal broken systems, we may have local circulating magnetization currents.
These do not contribute to the transport, but do show up in our result from the kubo formula.
Thus, to find the measurable transport current, these must be subtracted.
See chernodubThermalTransportGeometry2021

*** Brief discussion on Tatara vs Luttinger

*** Discussion about the stress energy tensor
Derive the stress energy tensor, comment on symmetric vs non-symmetric
Refer to Stoof

*** Derive Landau Levels

**** No tilt

**** With tilt
Show the transformation and use the no tilt result.

*** Analytical expressions for the operators
Do the general case
Discussion about the T tensor, etc.
Degeneracy factor from k sum:
- Write something like, "we will see that J and T are indep of kx, and we may extract a degeneracy factor"
- Cleaner than having it at the end?

*** Explicit form and total response

**** No tilt
Show the exact form of the matrix elements
Show how to simplify
Do the integral and write down resutl

**** Tilt
Find explicit forms of the matrix elements
How to separate in tx vs tz?

***** Tz tilt
In the case of only tz-tilt, the expression is easy to find, as only the energies are the only quantity that change.

In the case of inversion symmetry, we get divergences in the tz-integral.
We solve this by a momentum cutoff

For Type-II, we must restrict the limits of integration

Have computed the contrib form interband -N -> N + 1, must also find intraband

The goal: put on a solid foundation when the contributions from chiralitites cancel

*** Results

**** Tiltless

**** Tilt

***** Perp
- m,n plane contributions for different tx
- gamma_n total contribtion for different tx
- Differences between P and broken P

***** Parallell
-
-

*** Discussion of results

**** Momentum cutoff in the tz case

****

**** Show some widemann-franz, mottt, etc relations?

* Ideas
** Divergence in tz
From Stoof it seems like the magnetization goes to zero as T and mu goes to zero, however, there are two important questions.
Is the result valid for the limit that we are considering.
They say something about T=0 \omega whatever vs T whatever \omega = 0.
Also, does it matter that we have a background magnetic field, when calculating the magnetization?
One hope is that the magnetization will cancel our divergence.

** Extend to finite potential
Having a non-zero potential is very interesting, as this drastically changes the Fermi surface, particualrly for tilted systems
"The anomalous hall and nernst effect has beens shown to have interesting chemical potential dependence for tilted system..." (see ferreirosAnomalousNernstThermal2017)
