#+title: Outline

* Outline

** Topological materials

*** From high energy phsyics to condensed matter Dirac materials
Start from the Dirac Lagrangian, and show the Weyl decomposition
We exactly recover the Hamiltonian of a dirac cone
See chernodubThermalTransportGeometry2021 eq.~(2)

- Analagous theories in HEP and condensed matter
- Thermal transport, geometry, and anomalies bridge gap

- Introduction
- Dirac fermions haha
  Liquid (top page 5 in review)
- This is a field of some unification of low and high energy physics.
  The emergent Dirac and Weyl cones in condensed matter physics follow in beautiful analogy to their high energy counterparts.
  Problematic that some of the concepts of QFT and high energy physics is soemwhat inacceccible for condensed matter physisists.
  At the same time, condensed matter descriptions have been difficult to relate back to the QFT formalism.
  This crossing point offers rich insight both for high and low energy phsyics.
  Unfortunately, the different languages can cause some misunderstanding.
  Some phenomena have different names, while different pheomenta sometimes are mistaken for the same.
  See (reveiw paper) which attempts to unify the language of the two fields, highlight where subtle differences are imporant, and elucidate which assumptions are made.
- Dirac equation, massless may be decomposed to weyl equations
  - Dirac ... linear momenta ... lorentz invariance ....
  - Interestingly, ..., emergent phenomena in condensed matter ... linear momenta

*** Weyl and Dirac cones in condenset amtter phyiscs
- Basic equation, 2D gapped 3D not gapped.

- Extend to 4x4 by some other spin degree of freedom

- Add tilt

**** Tilted dirac cones
***** TODO Introduction
- Material realizations
***** From tight binding model to linear model
Clean up so that the symbol convention is consistent.
Make sure argument about the sign of this and that is legit

****** Validity of the linear model
- In particular, discuss something about the fermi surface
- Infinite dirac sea
- May need momentum cutoff
- Maybe tie in with graphene or other model?

***** Tilting term
****** Inversion symmetry vs no inversion symmetry
****** Fermi surface when tilting
See ferreirosAnomalousNernstThermal2017 for discussion
Limitation of linear model


** The response

*** Important considerations and observations
**** Magnetization currents
In time reversal broken systems, we may have local circulating magnetization currents.
These do not contribute to the transport, but do show up in our result from the kubo formula.
Thus, to find the measurable transport current, these must be subtracted.
See chernodubThermalTransportGeometry2021

**** Brief discussion on Tatara vs Luttinger

**** Discussion about the stress energy tensor
Derive the stress energy tensor, comment on symmetric vs non-symmetric
Refer to Stoof

*** Derive Landau Levels

**** No tilt

**** With tilt
Show the transformation and use the no tilt result.

*** Analytical expressions for the operators
Do the general case
Discussion about the T tensor, etc.
Degeneracy factor from k sum:
- Write something like, "we will see that J and T are indep of kx, and we may extract a degeneracy factor"
- Cleaner than having it at the end?

*** Explicit form and total response

**** No tilt
Show the exact form of the matrix elements
Show how to simplify
Do the integral and write down resutl

**** Tilt
Find explicit forms of the matrix elements
How to separate in tx vs tz?

***** DONE Show how to get the degeneracy factor form kx, as was done in beginning of 2.3.3


***** Tx tilt
Specialize to tz = 0

***** Tz tilt
In the case of only tz-tilt, the expression is easy to find, as only the energies are the only quantity that change.

In the case of inversion symmetry, we get divergences in the tz-integral.
We solve this by a momentum cutoff

For Type-II, we must restrict the limits of integration

Have computed the contrib form interband -N -> N + 1, must also find intraband

The goal: put on a solid foundation when the contributions from chiralitites cancel


*** Summary and discussion of results

**** Summary of results
Recap that all contributions were found for s=+1.
To find the contrib from the other chirality, use .... depending on symmetry.
Contributions separated into even and odd components in the figures.

For perp. tilt we get a scaled down contrib.
Independent(?) of the whether inversion symmetry is broken

For parallel. tilt, the situations is more complex.
Refer to figure.

**** Momentum cutoff in the tz case

****

**** Show some widemann-franz, mottt, etc relations?

** Further work

*** Tilt parallel to the temperature gradient, i.e. ty

*** Inclusion of finite chemical potential
See [[file:~/Documents/NTNU/10semester/meetings/05-30.org::*https://www.youtube.com/watch?v=Zu2Rzd6rkVQ&t=96s][Notes from Vozmediano YouTube video]] on why the chemical potential is important
In particular, something something only lowest landau level
I think acually the computation is quite easy in the untilted case.
I also suspect that this is quite interesting, as the fermi surface and region of only one LL drastically change with tilt.

*** More research into the energy-momentum tensor

* Ideas and Problems
** Directions
We have made certain choices of which directions we consider.
Specifically, we have chosen to specifically consider the perpendicular tilt to be parallell to the charge current.
It could also be perpendicular to the charge current, and parallell to the temperature gradient.
In that case (I think), we would get a more complicated form of the energy momentum tensor (as t_y) would appear.
It warrants a comment

** The energy-momentum tensor
We have chosen to use the canonical energy momentum tensor.
This warrants some discussion, and also we may include our calculation for the symmetric choice

In the beginning, we should compute, for a generally tilted system, the current and energy-momentum tensor.
A more in depth discussion on the choice is maybe more fitting in the results and discussion section

Quick notes and ideas
- Ignore the concept of the energy-momentum tensor entirely.
  The gravitational potential couple to the energy density, and we use the conservation of energy to include instead the energy flux.
  We should therefore find an expression of the energy flux (and hope that it coincides with the energy-momentum tensor).
  I believe maybe the argumentation in Stoof is along these lines.
- Currents and the Energy-Momentum Tensor in Classical Field Theory: A Fresh Look at an Old Problem
  Has some quite funny formulations on how the question of defining the T has puzzled physicists
  In Table 1. it looks like they use the symemtric T


** DONE [#A] Response not odd
Is it a problem that the tz typeii reponse is not odd in tz?
It measn that, for a symmetric system, there is a difference between having the positive chirality in positive direction and the negative chirality in positive direciton.
I.e., is the chiralitites something absolute, or should be the same after a redefinition of the chiralities?

*** DONE Check that the treatment of the sign in tz is consitent
Specifically, identify what makes the answer differ for different sign

** Divergence in tz
From Stoof it seems like the magnetization goes to zero as T and mu goes to zero, however, there are two important questions.
Is the result valid for the limit that we are considering.
They say something about T=0 \omega whatever vs T whatever \omega = 0.
Also, does it matter that we have a background magnetic field, when calculating the magnetization?
One hope is that the magnetization will cancel our divergence.

** Extend to finite potential
Having a non-zero potential is very interesting, as this drastically changes the Fermi surface, particualrly for tilted systems
"The anomalous hall and nernst effect has beens shown to have interesting chemical potential dependence for tilted system..." (see ferreirosAnomalousNernstThermal2017)
