#+title: Outline

* Outline

** Topological materials

*** From high energy phsyics to condensed matter Dirac materials
Start from the Dirac Lagrangian, and show the Weyl decomposition
We exactly recover the Hamiltonian of a dirac cone
See chernodubThermalTransportGeometry2021 eq.~(2)

** Type-II materials
- Introduction
- From tight binding model to linear model
- Tilting term
  - Inversion symmetry vs no inversion symmetry


** The response

*** Magnetization currents
In time reversal broken systems, we may have local circulating magnetization currents.
These do not contribute to the transport, but do show up in our result from the kubo formula.
Thus, to find the measurable transport current, these must be subtracted.
See chernodubThermalTransportGeometry2021

*** Brief discussion on Tatara vs Luttinger

*** Discussion about the stress energy tensor
Derive the stress energy tensor, comment on symmetric vs non-symmetric
Refer to Stoof

*** Derive Landau Levels

**** No tilt

**** With tilt
Show the transformation and use the no tilt result.

*** Analytical expressions for the operators
Do the general case
Discussion about the T tensor, etc.
Degeneracy factor from k sum:
- Write something like, "we will see that J and T are indep of kx, and we may extract a degeneracy factor"
- Cleaner than having it at the end?

*** Explicit form and total response

**** No tilt
Show the exact form of the matrix elements
Show how to simplify
Do the integral and write down resutl

**** Tilt
Find explicit forms of the matrix elements
How to separate in tx vs tz?

***** DONE Show how to get the degeneracy factor form kx, as was done in beginning of 2.3.3


***** Tx tilt
Specialize to tz = 0

***** Tz tilt
In the case of only tz-tilt, the expression is easy to find, as only the energies are the only quantity that change.

In the case of inversion symmetry, we get divergences in the tz-integral.
We solve this by a momentum cutoff

For Type-II, we must restrict the limits of integration

Have computed the contrib form interband -N -> N + 1, must also find intraband

The goal: put on a solid foundation when the contributions from chiralitites cancel

*** Results
/Move the results into the previous section??/

**** Tiltless

**** Tilt

***** Perp
- m,n plane contributions for different tx
- gamma_n total contribtion for different tx
- Differences between P and broken P

***** Parallell
-
-

*** Discussion of results

**** Momentum cutoff in the tz case

****

**** Show some widemann-franz, mottt, etc relations?

* Ideas and Problems
** The energy-momentum tensor
We have chosen to use the canonical energy momentum tensor.
This warrants some discussion, and also we may include our calculation for the symmetric choice

In the beginning, we should compute, for a generally tilted system, the current and energy-momentum tensor.
A more in depth discussion on the choice is maybe more fitting in the results and discussion section

Quick notes and ideas
- Ignore the concept of the energy-momentum tensor entirely.
  The gravitational potential couple to the energy density, and we use the conservation of energy to include instead the energy flux.
  We should therefore find an expression of the energy flux (and hope that it coincides with the energy-momentum tensor).
  I believe maybe the argumentation in Stoof is along these lines.

** [#A] Response not odd
Is it a problem that the tz typeii reponse is not odd in tz?
It measn that, for a symmetric system, there is a difference between having the positive chirality in positive direction and the negative chirality in positive direciton.
I.e., is the chiralitites something absolute, or should be the same after a redefinition of the chiralities?

** Divergence in tz
From Stoof it seems like the magnetization goes to zero as T and mu goes to zero, however, there are two important questions.
Is the result valid for the limit that we are considering.
They say something about T=0 \omega whatever vs T whatever \omega = 0.
Also, does it matter that we have a background magnetic field, when calculating the magnetization?
One hope is that the magnetization will cancel our divergence.

** Extend to finite potential
Having a non-zero potential is very interesting, as this drastically changes the Fermi surface, particualrly for tilted systems
"The anomalous hall and nernst effect has beens shown to have interesting chemical potential dependence for tilted system..." (see ferreirosAnomalousNernstThermal2017)
