* Notes from brainstorm
Overall mål med talen: Minne-tale, det vi har opplevd som kull

Kan bruke bilder


Engasjert kull, ref. Samf, NTNUI, Velferdstinget, Isfit, UKA Arena-sjef
Eirik på CERN, Joffa på reaktor, Anders vant stubban, olympiader,

** Fadderperioden
Faddergruppenavn, opplegg under fadderperioden, opptaket
Nerdegreier som siffer i pi, e, ...
Togafest, BTB, L2L
Historie om Nina sitt kollektiv:
- "De skulle ikke ha vors, men folk var så vant til at det alltid var vors der, så en gang dukket det bare noen opp 'jeg er klar for vors'. Og da ble det vors!"
NWA max gangsta. XXXintegration. Kulturfestivalen
- Forklare høyrehånd

For sent til julebohr

** Åre
Nevne Åre
Leilighetskompleks
Thomas brakk skien, Ole drakk 15 øl før vorset begynte
Systembolaget i Åre statistikk som funksjon av tid

** Div nabla
Nabla vant UKEtoget i 19 med raketten

UKAdemiet - vant case over f.eks. Janus. 25000kr
Se bilde på instagram

Kjelleren
Barnehagen

Fysikkland sin lyslogg og rapport

Ludøl

Div turer
fjellturer (snøhetta, rondane, ..), CERN, finnland,
ellers har folk vært på tur til krakow, ...., ...., ....

75 års jub, Iver sitat: "Jeg ser det stor variasjon i salen, ikke minst når det kommer til innteligens"
"Møtte dirac"

Titt i gamle Nablad etter bra sitat

** Div Samf
Samf..
Samf. 14 millioner i overskudd
Trukket inn av Pirum
Elsie fyller inn her

** Korona
Hva gjør man med korona?
+ ikke for mye depresivt
+ alle gjorde det samme
+ ekskursjon, utveksling
+ samf
+ Dagen alt stengte
  + Dra hjem fra sal
  + Ikke se den igjen på 2 år

** Div annet
Kjærestepar

Joffa gikk over grønland

Finnes det noen relaterbare master-titler?

Utmatrikulering
+ master er ikke ferdige
+ håndsopprekning på hvem som er ferdig
+ XXXintegration hadde håndsopprekning "hvem har levert, hvem er ferdige, hvem har begynt?"

Henrik sin elmag-opplevelse.

Midtsidebilde

Immball

** TODO var vi hos stovneng?
@NH

* Tale
"I denne forsamlingen er det en kolossal spennvidde, ikke minst i faglig dyktighet",
som vår kjære professor Iver Brevik sa i sin tale under Nablas 75-årsjubileum da vi gikk i førsteklasse.
(vi lot oss ikke skremme vekk så lett, så her står vi)
Når man ber folk om tips til hvordan man skal skrive en god tale, så går det gjerne igjen at man burde spille på nostalgi.
Trekk frem noe som man sammen har lidd seg gjennom sammen, som man kan samles om.
Da vi pratet sammen om denne talen innså vi at det ikke nødvendigvis var så lett, for vi har for det meste hatt det ganske fint sammen.
Både på og utenfor universitetets vegger har vi hatt et fint samhold og gode opplevelser, og det tenker vi å mimre om litt idag.
(pause)
...
(Elsie)
Men så kom vi på MekFys-, Elmag-, og Matte 4-eksamen, og innså at vi har hatt det litt kjipt sammen også.
(korona? Korona har sørget for at vi har hatt det litt kjipt uten å være sammen også)

Vårt første møte med Trondheim og hverandre var fadderperioden.
Noen av dere som faller under familie, venner og foresatte her i salen er vel kjent med hva fadderperioden er, men det er nok også mange som ikke kjenner så godt til dette fenomenet.
Når man kommer som ny student til ny by, med mange nye folk, er det kjekt at det er tilrettelagt med opplegg for at man raskere og lettere kan bli kjent med sin nye tilværelse og nye studievenner.
Linjeforeningene og NTNU har hver sin strategi for dette:
Linjeforeningene løser dette med et to-ukers program med fester, aktiviteter, og turer.
NTNU på sin side, har fulle arbeidsdager med "teknostart", der man blant ruller klinkekuler ned renner, skriver labjournal, og hører på forelesninger, på svensk, der stoffet er bevis av hawking radiation ved dimensjonsanalyse...
Kombinert utgjør dette to svært hektiske, men også minneverdige, uker, der man løper fra det ene til det andre, med knapt noe tid til å hive i seg en matbit mellom slagene.

Det er i fadderperioden man først opplever hvor fantastisk og anderledes fysmat er:
det er selvsagt fult med fester og sprell, men samtidig er det også memorisering av siffer i Pi og e, greske alfabet og studentviser.
Alle nerdene fra videregående samles innenfor en kritisk tetthet.
(Måtte jo få inn én dårlig fysikkvits her)

Vi kan ikke prate i all evighet om fadderperioden, men må jo raskt nevne:
(veldig fint om vi har bilder)
- TODO bilder
+ Togafest
+ btb
+ l2l
+ Nablas egen rappegruppe NWA som opptredde på max gangsta (høyrehåndsregel).
  + Jeg husker særlig da vi stod på samfundet, med NWA som sang om fysmat, og vi alle holdt oppe høyrehåndsregelen.

(Elsie sier noe om opptak)

Slik vi prater nå, teoriser kanskje noen av dere foresatte i salen at vi bare fester og morer oss, og ikke gjør noe arbeid.
Nok en gang er et sitat fra Iver Brevik passende:
Det er en svært elegant teori, det er bare det at den er feil.
Som Fysmattere jobber vi jo også hardt med studiene.
Fysmat er kjent som et av de mest krevende studiene på NTNU.
Ikke bare gjør Fysmattere det bra i studiene, men går til og med forbi det!
Vi har hatt folk som har jobbet ved CERN, andre har forsket på fusjonsreaktorer (finn ut av hva joffa egt driver med), for ikke å nevne alle de talløse vinnere og deltakere av diverse olympiader man finner her.

Selv kombinert med en hektisk studiehverdag, er det også flere som har engasjert seg i store viktige verv:
De fleste her har hatt verv i enten Nabla, UKA eller Samfundet.
vi har leder for Samfundet her, leder for NTNUI (hva drev øystein med?) og andre medlemmer i NTNUI sitt hovdestyre( er det det torstein er?). sjef for velferdstinget, og personer med verv med store ansvarsområder innen både UKA og Isfit.
(oda samf)

(UKA)

Vi husker jo alle 12. mars 2020.
Vi følte oss som kriminelle da vi gikk inn på skolen og hentet bøker fra pulten, og dro hjem.
Der ble vi sittende i de neste to år.
Det var jo kjipt at utvekslingen ble avlyst av korona, noe vi vet mange hadde gledet seg mye til.
Det var heldig at vi hvertfall fikk ekskursjonen som et lite plaster på såret... (kanskje elsie sier dette)
Og så trenger vi ikke si mer om det

(avsluting)
