#+TITLE: 02 28

* Minimal model and two cones
In the minimal model for Type II we have a 2x2 H with two momentum-separated cones.
If I understand correctly, we can extend the Hamiltonian to 4x4, and explicitly see the degeneracy of the spins.
Alternatively, we see that if the H is TR invariant, the spin flipped state is also an eigenstate??
So, are there really four cones in the minimal coupling, with two and two superimposed??

* Hamiltonian or energy band must be invariant symmetry?
Is it the Hamiltonian or energy band that must be invariant under a symmetry?
Take, for example, \(H=v_{F} k \sigma \).
Under time reversal, \(k\to -k, \sigma \to -\sigma \), it is obviously invariant.
However, under inversion, \(k\to -k, \sigma \to \sigma \), it is not, but the energy bands are.

How does this relate to the 2x2 vs 4x4?
When extending to 4x4, many of the symmetries are explicitly present

* What I have done since last time:

** Looked at the symmetry of the system

** Moved forward with the calculations for the tilted cone
Boost into a untilted frame
We get eigenvalues and eigenfunctions similar to what we had before, but with some extra terms and prefactors

I think this is a good way of making progress and better understand the problem.

*** Is the extra term in current operator correct?

*** Currently only do temperature gradient in the same direction as the tilt

* TODO Consider hole vs electron carrier when overtilt

* TODO C operator

* TODO Lorentz invariance
