#+title: 06 07

* Talk with Maria et al next week

** How exotic is this?
Which papers are relevant?

** Energy-momentum tensor

** Discussion similar to generation paper

** Tilt in y-direction

** Log \(\Lambda\)
Looked in Asgari paper (see [[file:05-30.org::*Effecitve fermi velocity from cutoff][Effecitve fermi velocity from cutoff]] )
Alireza seemed happy wiht \(\Lambda = \frac{k_c}{\sqrt{2 e B}} \) where \( k_c \propto 1 / a \).

* Physica print

** TODO Find out what the prices are and send to Alireza

* Draft
Did not really get a clear answer.
Should probably be more firm and ask for feedback on draft before some date.

* Issue of magnetization current
Alireza wanted to know what happens with magnetization curent for Type-II
Stoof seems to conclude that the magnetization current is zero for zero chemical potential and temperature, however, this calculation might be only for type i.
Eq.(64) in stoof seems to depend on the denisty of states at the some energy level. Maybe this is greatly changed by the fact the density of states is changed at the fermi level for type II?
